/**************************************************************************
 *   editorkeys.c                                                         *
 *                                                                        *
 *   Copyright (C) 1999-2003 Chris Allegretta                             *
 *   Copyright (C) 2010-2018 PCR                                          *
 *                                                                        *
 *   This program is free software; you can redistribute it and/or modify *
 *   it under the terms of the GNU General Public License as published by *
 *   the Free Software Foundation; either version 2, or (at your option)  *
 *   any later version.                                                   *
 *                                                                        *
 *   This program is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of       *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
 *   GNU General Public License for more details.                         *
 *                                                                        *
 *   You should have received a copy of the GNU General Public License    *
 *   along with this program; if not, write to the Free Software          *
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.            *
 *                                                                        *
 **************************************************************************/

#include "headers.h"

func_key_t editor_func_key_table[] = {
//       1234567890123456789012   123456789012345678901234567890
// 123456789,123456789,123456789,123456789     123456789012345678901234567890
 {EFNM, "Menu",                  "0: Previous Menu",
  {K_ESC    ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFLM, "Menu",                  "Previous Menu",
  {K_M_BAKQT,K_M_TILDE,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },

 {EFAM, "",                      "1: Editor - File Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFNM, "Close",                 "Close file",
  {K_C_q    ,KNA      ,KNA      ,KNA      },F_I(doe_close_file_ask),      get_str_none },
 {EFNM, "Close always",          "Close file always",
  {K_MC_q   ,KNA      ,KNA      ,KNA      },F_I(doe_close_file_always),   get_str_none },
 {EFNM, "Close All files",       "Close all files",
  {K_M_q    ,KNA      ,KNA      ,KNA      },F_I(doe_close_all_ask),       get_str_none },
 {EFNM, "Close All modified",    "Close all files modified",
  {K_M_Q    ,KNA      ,KNA      ,KNA      },F_I(doe_close_all_always),    get_str_none },
 {EFLM, "Quit",                  "Quit editor (Viewer mode)",
  {K_ESC    , K_q_     ,K_C_q    ,K_M_q   },F_I(doe_quit),                get_str_none },
 {EFNM, "Open file",             "Open file",
  {K_M_e    ,KNA      ,KNA      ,KNA      },F_I(doe_open_file_recursive), get_str_none },
 {EFNM, "Open file(RO)",         "View file (Read-Only)",
  {K_M_E    ,KNA      ,KNA      ,KNA      },F_I(doe_open_file_ro),        get_str_none },
 {EFNM, "Open locked file",      "Open locked file",
  {K_MC_e   ,KNA      ,KNA      ,KNA      },F_I(doe_open_file_locked),    get_str_none },
 {EFNM, "Open New File",         "Open new file",
  {K_M_n    ,K_M_N    ,KNA      ,KNA      },F_I(doe_open_new_file),       get_str_none },
 {EFNM, "Reopen",                "Reopen file",
  {K_C_z    ,KNA      ,KNA      ,KNA      },F_I(doe_reopen_file),         get_str_none },
 {EFNM, "Reopen, goto Last pos.","Reopen and go to Last line",
  {K_M_Z    ,KNA      ,KNA      ,KNA      },F_I(doe_reopen_file_last_line),get_str_none },
 {EFNM, "Write File as",         "Write file as",
  {K_M_S    ,KNA      ,KNA      ,KNA      },F_I(doe_write_file_to),       get_str_none },
 {EFNM, "Write File",            "Write file",
  {K_M_w    ,KNA      ,KNA      ,KNA      },F_I(doe_write_file_ask),      get_str_none },
 {EFNM, "Write File always.",    "Write file always",
  {K_M_W    ,KNA      ,KNA      ,KNA      },F_I(doe_write_file_modified), get_str_none },
 {EFNM, "Write All",             "Write all files",
  {K_M_A    ,KNA      ,KNA      ,KNA      },F_I(doe_write_all_ask),       get_str_none },
 {EFNM, "Write All Modif.",      "Write all files modified",
  {K_MC_a   ,KNA      ,KNA      ,KNA      },F_I(doe_write_all_modified),  get_str_none },
 {EFNM, "Open Files",            "Open files in buffer",
  {K_M_L    ,KNA      ,KNA      ,KNA      },F_I(doe_open_files_in_buf),   get_str_none },
 {EFNM, "Read into buffer",      "Read file into current pos",
  {K_M_i    ,KNA      ,KNA      ,KNA      },F_I(doe_read_file_into_cur_buf),get_str_none },
#ifdef ENABLE_FILER
 {EFAM, "Open filer",            "Open filer",
  {K_M_F    ,K_MC_f   ,KNA      ,KNA      },F_I(doe_filer_with_dir),      get_str_none },
#endif // ENABLE_FILER

 {EFAM, "",                      "2: Editor - Cursor Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFAM, "Up",                    "Move cursor UP",
  {K_C_e    ,K_UP     ,KNA      ,KNA      },F_I(doe_up),                  get_str_none },
 {EFAM, "Down",                  "Move cursor DOWN",
  {K_C_x    ,K_DOWN   ,KNA      ,KNA      },F_I(doe_down),                get_str_none },
 {EFNM, "Left",                  "Move cursor LEFT",
  {K_C_s    ,K_LEFT   ,KNA      ,KNA      },F_I(doe_left),                get_str_none },
 {EFNM, "Right",                 "Move cursor RIGHT",
  {K_C_d    ,K_RIGHT  ,KNA      ,KNA      },F_I(doe_right),               get_str_none },
 {EFAM, "Page up",               "Page UP",
  {K_PPAGE  ,KNA      ,KNA      ,KNA      },F_I(doe_page_up),             get_str_none },
 {EFAM, "half Page up",          "half Page UP",
  {K_C_r    ,KNA      ,KNA      ,KNA      },F_I(doe_half_page_up),        get_str_none },
 {EFAM, "Page down",             "Page DOWN",
  {K_NPAGE  ,KNA      ,KNA      ,KNA      },F_I(doe_page_down),           get_str_none },
 {EFAM, "half Page down",        "half Page DOWN",
  {K_C_c    ,KNA      ,KNA      ,KNA      },F_I(doe_half_page_down),      get_str_none },
 {EFLM, "Page up(list)",         "Page UP(list mode)",
  {K_C_s    ,K_LEFT   ,KNA      ,KNA      },F_I(doe_half_page_up),        get_str_none },
 {EFLM, "Page down(list)",       "Page DOWN(list mode)",
  {K_C_d    ,K_RIGHT  ,KNA      ,KNA      },F_I(doe_half_page_down),      get_str_none },
 {EFAM, "Prev Word",             "Move backward one word",
  {K_C_a    ,KNA      ,KNA      ,KNA      },F_I(doe_prev_word),           get_str_none },
 {EFAM, "Next Word",             "Move forward one word",
  {K_C_f    ,KNA      ,KNA      ,KNA      },F_I(doe_next_word),           get_str_none },
 {EFAM, "Start of line",         "Start of the line",
  {K_C_t    ,K_HOME   ,KNA      ,KNA      },F_I(doe_start_of_line),       get_str_none },
 {EFAM, "End of line",           "End of the line",
  {K_C_b    ,K_C_v    ,K_END    ,KNA      },F_I(doe_end_of_line),         get_str_none },
 {EFAM, "First line",            "Top of the buffer",
  {K_M_t    ,KNA      ,KNA      ,KNA      },F_I(doe_first_line),          get_str_none },
 {EFAM, "Last line",             "Bottom of the buffer",
  {K_M_b    ,KNA      ,KNA      ,KNA      },F_I(doe_last_line),           get_str_none },
 {EFAM, "Go To Line",            "Go to specified line and column",
  {K_C_UNDLN,KNA      ,KNA      ,KNA      },F_I(doe_goto_line),           get_str_none },
 {EFAM, "Goto columns",          "Goto columns in the line",
  {K_C_AT   ,KNA      ,KNA      ,KNA      },F_I(doe_goto_column),         get_str_none },
 {EFAM, "TagJp",                 "Tag-jump to file/dir curs",
  {K_F11    ,K_M_J    ,KNA      ,KNA      },F_I(doe_tag_jump_in_cur_col), get_str_none },
 {EFAM, "TagJp",                 "Tag-jump to file/dir line",
  {K_F12    ,K_M_j    ,KNA      ,KNA      },F_I(doe_tag_jump_in_cur_line),get_str_none },
#ifdef ENABLE_FILER
 {EFAM, "ToDir",                 "Goto directory curs",
  {K_S_F11  ,K_M_UNDLN,KNA      ,KNA      },F_I(doe_goto_dir_in_cur_col), get_str_none },
 {EFAM, "ToDir",                 "Goto directory line",
  {K_S_F12  ,K_M_PLUS ,KNA      ,KNA      },F_I(doe_goto_dir_in_cur_line),get_str_none },
#endif // ENABLE_FILER

 {EFAM, "",                      "3: Editor - Editing Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFNM, "Tab",                   "Insert a TAB character",
  {K_TAB    ,KNA      ,KNA      ,KNA      },F_I(doe_tab),                 get_str_none },
 {EFNM, "Enter",                 "Insert a carriage return",
  {K_ENTER  ,KNA      ,KNA      ,KNA      },F_I(doe_carriage_return),     get_str_none },
 {EFNM, "Enter w auto indent",   "Insert a carriage return",
  {K_M_ENTER,KNA      ,KNA      ,KNA      },F_I(doe_carriage_return_indent),get_str_none },
 {EFNM, "Backspace",             "Backspace",
  {K_C_h    ,AK_BS    ,KNA      ,KNA      },F_I(doe_backspace),           get_str_none },
 {EFNM, "Backspace(limited)",     "Backspace(limited)",
  {K_MC_h   ,AK_M_BS  ,KNA      ,KNA      },F_I(doe_backspace_limited),   get_str_none },
 {EFNM, "Delete",                "Delete a character",
  {K_C_g    ,AK_DEL   ,KNA      ,KNA      },F_I(doe_delete_char),         get_str_none },
 {EFNM, "Delete(limited)",       "Delete a character(limited)",
  {K_MC_g   ,AK_M_DEL ,KNA      ,KNA      },F_I(doe_delete_char_limited), get_str_none },
 {EFNM, "UpperLower",            "Invert upper/lower letter",
  {K_C_w    ,KNA      ,KNA      ,KNA      },F_I(doe_conv_upp_low_letter), get_str_none },
 {EFNM, "UpperLetter",           "Make upper letter",
  {K_M_U   ,KNA      ,KNA      ,KNA      },F_I(doe_conv_low_letter),     get_str_none },
 {EFNM, "Ctrl code",             "Input control code",
  {K_M_EXCLA,KNA      ,KNA      ,KNA      },F_I(doe_control_code),        get_str_none },
 {EFNM, "Char code",             "Input character code",
  {K_M_AT   ,KNA      ,KNA      ,KNA      },F_I(doe_charcode),            get_str_none },
 {EFNM, "Fill spaces",           "Fill spaces till the columns",
  {K_M_APOST,KNA      ,KNA      ,KNA      },F_I(doe_fill_spaces_to_columns),get_str_none },
 {EFNM, "Paste history",         "Paste from history",
  {K_M_h    ,KNA      ,KNA      ,KNA      },F_I(doe_paste_from_history),  get_str_none },
#ifdef ENABLE_UNDO
 {EFNM, "Undo",                  "Undo",
  {K_M_u    ,K_M_z    ,KNA      ,KNA      },F_I(doe_undo),                get_str_none },
 {EFNM, "Redo",                  "Redo",
  {K_M_o    ,KNA      ,KNA      ,KNA      },F_I(doe_redo),                get_str_none },
#endif // ENABLE_UNDO
 {EFLM, "Enter text",            "Enter text in the cur line",
  {K_ENTER  ,KNA      ,KNA      ,KNA      },F_I(doe_enter_text),          get_str_none },
 {EFLM, "Enter text",            "Enter text in the cur line",
  {K_M_ENTER,KNA      ,KNA      ,KNA      },F_I(doe_enter_text_add),      get_str_none },

 {EFAM, "",                      "4: Editor - Search/Replace Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFAM, "SrchB",                 "Search keyword forward",
  {K_C_RBRAK,K_S_F03  ,KNA      ,KNA      },F_I(doe_search_first_backward),get_str_none },
 {EFAM, "SrchF",                 "Search keyword backward",
  {K_C_BAKSL,K_S_F04  ,KNA      ,KNA      },F_I(doe_search_first_forward),get_str_none },
 {EFAM, "SrchB",                 "Search keyword backward again",
  {K_M_a    ,K_M_s    ,K_F03    ,KNA      },F_I(doe_search_next_backward),get_str_none },
 {EFAM, "SrchF",                 "Search keyword forward again",
  {K_M_f    ,K_M_d    ,K_F04    ,KNA      },F_I(doe_search_next_forward), get_str_none },
 {EFNM, "Replace",               "Replace keyword",
  {K_C_CARET,KNA      ,KNA      ,KNA      },F_I(doe_replace),             get_str_none },
#ifdef ENABLE_REGEX
 {EFNM, "Find Bracket()",        "Find counter bracket()",
  {K_M_RBRAK,KNA      ,KNA      ,KNA      },F_I(doe_find_bracket),        get_str_none },
 {EFNM, "Find Bracket)(",        "Find counter bracket)(",
  {K_M_LBRAK,KNA      ,KNA      ,KNA      },F_I(doe_find_bracket_reverse),get_str_none },
 {EFNM, "Find Brackets(())",     "Find counter brackets(())",
  {K_M_RBRAC,KNA      ,KNA      ,KNA      },F_I(doe_find_brackets),        get_str_none },
 {EFNM, "Find Brackets))((",     "Find counter brackets))((",
  {K_M_LBRAC,KNA      ,KNA      ,KNA      },F_I(doe_find_brackets_reverse),get_str_none },
#endif // ENABLE_REGEX
 {EFNM, "RecKM",                 "Start/Stop recording key-macro",
  {K_F01    ,K_M_r    ,KNA      ,KNA      },F_I(doe_start_rec__cancel_rec),get_str_none },
 {EFNM, "PlbKM",                 "End-rec/Playback key-macro",
  {K_F02    ,K_M_p    ,KNA      ,KNA      },F_I(doe_end_rec__playback),   get_str_none },
 {EFNM, "Playback-1",            "Playback 1st latest key-macro",
  {K_M_1    ,KNA      ,KNA      ,KNA      },F_I(doe_playback_last_1),     get_str_none },
#ifdef ENABLE_HISTORY
 {EFNM, "Playback-string",       "Playback input string",
  {K_M_2    ,KNA      ,KNA      ,KNA      },F_I(doe_playback_string),     get_str_none },
#endif // ENABLE_HISTORY
 {EFAM, "Run line soon(logging)","Run current line soon w/ log",
  {K_M_x    ,KNA      ,KNA      ,KNA      },F_I(doe_run_line_immediate),  get_str_none },
 {EFAM, "Run command",           "Run command input",
  {K_M_X    ,KNA      ,KNA      ,KNA      },F_I(doe_run_line_input),      get_str_none },

 {EFAM, "",                      "5: Editor - Buffer Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFAM, "Previous buffer",       "Switch to previous file",
  {K_M_COMMA,KNA      ,KNA      ,KNA      },F_I(doe_switch_to_prev_buffer),get_str_none },
 {EFAM, "Next buffer",           "Switch to next file",
  {K_M_PERIO,KNA      ,KNA      ,KNA      },F_I(doe_switch_to_next_buffer),get_str_none },
 {EFAM, "Top of buffers",        "Switch to top of buffers",
  {K_M_LESST,KNA      ,KNA      ,KNA      },F_I(doe_switch_to_prev_bufs_boundary),get_str_none },
 {EFAM, "Bottom of buffers",     "Switch to bottom of buffers",
  {K_M_GREAT,KNA      ,KNA      ,KNA      },F_I(doe_switch_to_next_bufs_boundary),get_str_none },
 {EFNM, "Open project file",     "Open project file",
  {K_M_P    ,KNA      ,KNA      ,KNA      },F_I(doe_open_proj_file),      get_str_none },
 {EFNM, "Open exec. log file",   "Open exec. log file",
  {K_M_l    ,KNA      ,KNA      ,KNA      },F_I(doe_open_exec_log_file),  get_str_none },
 {EFNM, "Goto prev. pos",        "Goto previous pos.",
  {K_M_SLASH,KNA      ,KNA      ,KNA      },F_I(doe_return_to_prev_file_pos),get_str_none },
#ifdef ENABLE_HELP
 {EFNM, "Splash",                "Splash screen",
  {K_M_v    ,KNA      ,KNA      ,KNA      },F_I(doe_splash),              get_str_none },
 {EFNM, "File List",             "Display File List",
  {K_M_SEMCO,KNA      ,KNA      ,KNA      },F_I(doe_view_file_list),      get_str_none },
 {EFNM, "Key List",              "Display Key List",
  {K_M_QUEST,KNA      ,KNA      ,KNA      },F_I(doe_view_func_list),      get_str_none },
#endif // ENABLE_HELP

 {EFAM, "",                      "6: Editor - Cut-buffer Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFAM, "Mark ",                 "Mark text",
  {K_F05    ,K_C_n    ,K_M_5    ,KNA      },F_I(doe_tog_mark),            get_str_none },
 {EFNM, "Select all",            "Select all of buffer",
  {K_S_F05  ,K_M_PERCE,KNA      ,KNA      },F_I(doe_select_all_lines),    get_str_none },
 {EFNM, "Del  ",                 "Delete text",
  {K_M_k    ,K_M_CARET,KNA      ,KNA      },F_I(doe_delete_text),         get_str_none },
 {EFNM, "Cut  ",                 "Cut into Cut-buffer",
  {K_F06    ,K_C_k    ,K_M_6    ,KNA      },F_I(doe_cut_text),            get_str_none },
 {EFNM, "Cut into clip-board",   "Cut into clip-board",
  {K_S_F06  ,K_M_K    ,KNA      ,KNA      },F_I(doe_cut_text_to_sys_clipboard),get_str_none },
 {EFAM, "Copy ",                 "Copy to Cut-buffer",
  {K_F07    ,K_M_7    ,KNA      ,KNA      },F_I(doe_copy_text),           get_str_none },
 {EFAM, "Copy to clip-board",    "Copy to clip-board",
  {K_S_F07  ,K_M_AMPSD,KNA      ,KNA      },F_I(doe_copy_text_to_sys_clipboard),get_str_none },
 {EFNM, "Paste",                 "Paste from Cut-buf",
  {K_F08    ,K_M_8    ,KNA      ,KNA      },F_I(doe_paste_text_with_pop), get_str_none },
 {EFNM, "PasteChr",              "Paste from Cut-buf as a stream",
  {K_S_F08  ,K_M_ASTER,KNA      ,KNA      },F_I(doe_paste_text_with_pop_char),get_str_none },
 {EFNM, "Paste",                 "Paste from Cut-buf without pop",
  {K_F09    ,K_M_9    ,K_INS    ,KNA      },F_I(doe_paste_text_without_pop),get_str_none },
 {EFNM, "PasteChr",              "Paste from Cut-buf as a stream",
  {K_S_F09  ,K_M_LPARE,KNA      ,KNA      },F_I(doe_paste_text_without_pop_char),get_str_none },
 {EFNM, "Dupli",                 "Duplicate line",
  {K_F10    ,K_M_0    ,KNA      ,KNA      },F_I(doe_duplicate_text),      get_str_none },
 {EFNM, "CutToHead",             "Cut to head of the line",
  {K_C_j    ,KNA      ,KNA      ,KNA      },F_I(doe_cut_to_head),         get_str_none },
 {EFNM, "CutToTail",             "Cut to tail of the line",
  {K_C_l    ,KNA      ,KNA      ,KNA      },F_I(doe_cut_to_tail),         get_str_none },
 {EFNM, "DeleteToHead",          "Delete to head of the line",
  {K_C_u    ,KNA      ,KNA      ,KNA      },F_I(doe_delete_to_head),      get_str_none },
 {EFNM, "DeleteToTail",          "Delete to tail of the line",
  {K_C_o    ,KNA      ,KNA      ,KNA      },F_I(doe_delete_to_tail),      get_str_none },

 {EFAM, "",                      "7: Editor - Mode Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFAM, "App mode",              "Application mode",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_inc_app_mode),        get_str_app_mode },
 {EFNM, "Split pane",            "Split screen into panes",
  {K_M_VERTB,KNA      ,KNA      ,KNA      },F_I(doe_tog_panes),           get_str_editor_panes },
 {EFAM, "Switch pane",           "Switch editor pane",
  {K_M_TAB  ,K_M_BAKSL,KNA      ,KNA      },F_I(doe_tog_panex),           get_str_editor_panex },
 {EFNM, "Draw cursor",           "Toggle Drawing cursor",
  {K_MC_c   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_draw_cursor),     get_str_draw_cursor },
 {EFNM, "Ignore case",           "Toggle Ignore case",
  {K_M_G    ,KNA      ,KNA      ,KNA      },F_I(doe_tog_ignore_case),     get_str_ignore_case },
 {EFNM, "Back up files",         "Increment Back up files",
  {K_MC_b   ,KNA      ,KNA      ,KNA      },F_I(doe_inc_backup_files),    get_str_backup_files },
#ifdef ENABLE_REGEX
 {EFNM, "RegExp",                "Toggle Regex search/replace",
  {K_MC_x   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_regexp),          get_str_regexp },
#endif // ENABLE_REGEX
 {EFNM, "Cursor positioning",    "Increment Cursor pos. mode",
  {K_MC_s   ,KNA      ,KNA      ,KNA      },F_I(doe_inc_curs_pos_mode),   get_str_curs_pos_mode },
 {EFNM, "Dual scroll",           "Toggle Dual scroll",
  {K_MC_d   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_dual_scroll),     get_str_dual_scroll },
 {EFNM, "Show ruler",            "Toggle Show Ruler",
  {K_MC_r   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_show_ruler),      get_str_show_ruler },
 {EFNM, "Show line number",      "Toggle Show Line number",
  {K_MC_n   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_show_line_num),   get_str_show_line_num },
#ifdef ENABLE_SYNTAX
 {EFNM, "Syntax HL",             "Toggle Syntax Highlighting",
  {K_MC_y   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_syntax_hl),       get_str_syntax_hl },
 {EFNM, "TAB/EOL notation",      "Toggle TAB/EOL notation",
  {K_MC_z   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_tab_eol_notat),   get_str_tab_eol_notat },
#endif // ENABLE_SYNTAX

 {EFAM, "",                      "8: Editor - Buffer Mode Menu",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_menu_0),              get_str_none },
 {EFNM, "nix format",            "Set nix format (LF)",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_nix_file),    get_str_buf_nix_file },
 {EFNM, "Mac format",            "Set Mac format (CR)",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_mac_file),    get_str_buf_mac_file },
 {EFNM, "DOS format",            "Set DOS format (CR+LF)",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_dos_file),    get_str_buf_dos_file },
 {EFNM, "ASCII  encoding",       "Set ASCII  encoding",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_enc_ascii),   get_str_buf_enc_ascii },
 {EFNM, "UTF-8  encoding",       "Set UTF-8  encoding",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_enc_utf8),    get_str_buf_enc_utf8 },
#ifdef USE_NKF
 {EFNM, "EUC-JP encoding",       "Set EUC-JP encoding",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_enc_eucjp),   get_str_buf_enc_eucjp },
 {EFNM, "S-JIS  encoding",       "Set S-JIS  encoding",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_enc_sjis),    get_str_buf_enc_sjis },
 {EFNM, "JIS    encoding",       "Set JIS    encoding",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_enc_jis),     get_str_buf_enc_jis },
#endif // USE_NKF
 {EFNM, "BINARY encoding",       "Set BINARY encoding",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_set_buf_enc_binary),  get_str_buf_enc_binary },
 {EFNM, "Tab size",              "Toggle Tab size",
  {K_MC_t   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_buf_tab_size),    get_str_buf_tab_size },
 {EFNM, "Tab size",              "Increment Tab size",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(doe_inc_buf_tab_size),    get_str_buf_tab_size },
 {EFNM, "Line-wrap mode",        "Toggle Line-wrap mode",
  {K_MC_w   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_buf_line_wrap),   get_str_buf_line_wrap },
 {EFNM, "Locked",                "Toggle Locked",
  {K_MC_u   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_buf_locked),      get_str_buf_locked },
 {EFNM, "Display key list",      "Increment Displaying key list",
  {K_MC_k   ,KNA      ,KNA      ,KNA      },F_I(doe_inc_key_list_lines),  get_str_key_list_lines },
 {EFAM, "Show line number",      "Toggle Map key CDEL to BS",
  {K_MC_v   ,KNA      ,KNA      ,KNA      },F_I(doe_tog_map_key_7f_bs),   get_str_map_key_7f_bs },

 {EFAM, "",                      "",
  {KNA      ,KNA      ,KNA      ,KNA      },F_I(NULL), NULL },
};

// End of editorkeys.c
