/**************************************************************************
 *   editorkeys.c                                                         *
 *                                                                        *
 *   Copyright (C) 1999-2003 Chris Allegretta                             *
 *   Copyright (C) 2010-2018 PCR                                          *
 *                                                                        *
 *   This program is free software; you can redistribute it and/or modify *
 *   it under the terms of the GNU General Public License as published by *
 *   the Free Software Foundation; either version 2, or (at your option)  *
 *   any later version.                                                   *
 *                                                                        *
 *   This program is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of       *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
 *   GNU General Public License for more details.                         *
 *                                                                        *
 *   You should have received a copy of the GNU General Public License    *
 *   along with this program; if not, write to the Free Software          *
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.            *
 *                                                                        *
 **************************************************************************/

#include "headers.h"

func_key_t editor_func_key_table[] = {
//       1234567890123456789012   123456789012345678901234567890
// 123456789012345678901234       123456789012345678901234567890
 {EFNM, "Menu",                  "Previous Menu",
   {K_ESC,         KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFLM, "Menu",                  "Previous Menu",
   {K_ESC,         KNA, KNA}, F_I(doe_quit_editor),                get_str_setting_none },

 {EFNM, "",                      "Editor File Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFNM, "Open file",             "Open file",
   {K_M_e,         KNA, KNA}, F_I(doe_open_file_recursive),        get_str_setting_none },
 {EFNM, "Open file(RO)",         "View file (Read-Only)",
   {K_M_E,         KNA, KNA}, F_I(doe_open_file_ro),               get_str_setting_none },
 {EFNM, "Open locked file",      "Open locked file",
   {K_MC_E,        KNA, KNA}, F_I(doe_open_file_locked),           get_str_setting_none },
 {EFNM, "Open New File",         "Open new file",
   {K_M_n, K_M_N,       KNA}, F_I(doe_open_new_file),              get_str_setting_none },
 {EFLM, "Enter text",            "Enter text in the cur line",
   {K_M_e, K_M_n, K_ENTER  }, F_I(doe_enter_text),                 get_str_setting_none },
 {EFLM, "Enter text",            "Enter text in the cur line",
   {K_M_E, K_M_N, K_M_ENTER}, F_I(doe_enter_text_add),             get_str_setting_none },
 {EFNM, "Reopen",                "Reopen file",
   {K_C_Z,         KNA, KNA}, F_I(doe_reopen_file),                get_str_setting_none },
 {EFNM, "Reopen, goto Last pos.","Reopen and go to Last line",
   {K_M_Z,         KNA, KNA}, F_I(doe_reopen_file_last_line),      get_str_setting_none },
 {EFNM, "Write File as",         "Write file as",
   {K_M_S,         KNA, KNA}, F_I(doe_write_file_to),              get_str_setting_none },
 {EFNM, "Write File",            "Write file",
   {K_M_w,         KNA, KNA}, F_I(doe_write_file_ask),             get_str_setting_none },
 {EFNM, "Write File always.",    "Write file always",
   {K_M_W,         KNA, KNA}, F_I(doe_write_file_always),          get_str_setting_none },
 {EFNM, "Write All",             "Write all files",
   {K_M_A,         KNA, KNA}, F_I(doe_write_all_ask),              get_str_setting_none },
 {EFNM, "Write All Modif.",      "Write all files modified",
   {K_MC_A,        KNA, KNA}, F_I(doe_write_all_modified),         get_str_setting_none },
 {EFNM, "Close",                 "Close file",
   {K_C_Q,         KNA, KNA}, F_I(doe_close_file_ask),             get_str_setting_none },
 {EFLM, "Quit",                  "Quit editor",
   {K_C_Q, K_M_q,       KNA}, F_I(doe_quit_editor),                get_str_setting_none },
 {EFNM, "Close always",          "Close file always",
   {K_MC_Q,        KNA, KNA}, F_I(doe_close_file_always),          get_str_setting_none },
 {EFNM, "Close All files",       "Close all files",
   {K_M_q,         KNA, KNA}, F_I(doe_close_all_ask),              get_str_setting_none },
 {EFNM, "Close All modified",    "Close all files modified",
   {K_M_Q,         KNA, KNA}, F_I(doe_close_all_modified),         get_str_setting_none },
 {EFNM, "Open Files",            "Open files in buffer",
   {K_M_L,         KNA, KNA}, F_I(doe_open_files_in_buf),          get_str_setting_none },
 {EFNM, "Read into buffer",      "Read file into current pos",
   {K_M_i,         KNA, KNA}, F_I(doe_read_file_into_cur_buf),     get_str_setting_none },
#ifdef ENABLE_FILER
 {EFAM, "Open filer",            "Open filer",
   {K_M_F,         KNA, KNA}, F_I(doe_filer),                      get_str_setting_none },
#endif // ENABLE_FILER

 {EFNM, "",                      "Editor Cursor Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFAM, "Up",                    "Move cursor UP",
   {K_C_E, K_UP,        KNA}, F_I(doe_up),                         get_str_setting_none },
 {EFAM, "Down",                  "Move cursor DOWN",
   {K_C_X, K_DOWN,      KNA}, F_I(doe_down),                       get_str_setting_none },
 {EFNM, "Left",                  "Move cursor LEFT",
   {K_C_S, K_LEFT,      KNA}, F_I(doe_left),                       get_str_setting_none },
 {EFNM, "Right",                 "Move cursor RIGHT",
   {K_C_D, K_RIGHT,     KNA}, F_I(doe_right),                      get_str_setting_none },
 {EFLM, "Previous buffer",       "Switch to previous file",
   {K_C_S, K_LEFT,      KNA}, F_I(doe_switch_to_prev_buffer),      get_str_setting_none },
 {EFLM, "Next buffer",           "Switch to next file",
   {K_C_D, K_RIGHT,     KNA}, F_I(doe_switch_to_next_buffer),      get_str_setting_none },
 {EFAM, "Page up  ",             "Page UP",
   {K_C_R, K_PPAGE,     KNA}, F_I(doe_page_up),                    get_str_setting_none },
 {EFAM, "Page down",             "Page DOWN",
   {K_C_C, K_NPAGE,     KNA}, F_I(doe_page_down),                  get_str_setting_none },
 {EFAM, "Prev Word",             "Move backward one word",
   {K_C_A,         KNA, KNA}, F_I(doe_prev_word),                  get_str_setting_none },
 {EFAM, "Next Word",             "Move forward one word",
   {K_C_F,         KNA, KNA}, F_I(doe_next_word),                  get_str_setting_none },
 {EFAM, "Goto columns",          "Goto columns in the line",
   {K_MC_F,        KNA, KNA}, F_I(doe_goto_column),                get_str_setting_none },
 {EFAM, "Start of line",         "Start of the line",
   {K_C_T, K_HOME,      KNA}, F_I(doe_start_of_line),              get_str_setting_none },
 {EFAM, "End of line",           "End of the line",
   {K_C_B, K_C_V, K_END    }, F_I(doe_end_of_line),                get_str_setting_none },
 {EFAM, "First line",            "Top of the file",
   {K_M_t,         KNA, KNA}, F_I(doe_first_line),                 get_str_setting_none },
 {EFAM, "Last line",             "Bottom of the file",
   {K_M_b,         KNA, KNA}, F_I(doe_last_line),                  get_str_setting_none },
 {EFAM, "Go To Line",            "Go to specified line",
   {K_C_UNDLN,     KNA, KNA}, F_I(doe_goto_line),                  get_str_setting_none },
#ifdef ENABLE_FILER
 {EFAM, "ToDir",                 "Goto directory",
   {K_M_LBRAC,     KNA, KNA}, F_I(doe_goto_dir_in_cur_curs_pos),   get_str_setting_none },
 {EFAM, "ToDir",                 "Goto directory",
   {K_M_RBRAC,     KNA, KNA}, F_I(doe_goto_dir_in_cur_line),       get_str_setting_none },
#endif // ENABLE_FILER
 {EFAM, "TagJp",                 "Tag-jump to file or directory",
   {K_F11, K_M_J,       KNA}, F_I(doe_tag_jump_in_cur_curs_pos),   get_str_setting_none },
 {EFAM, "TagJp",                 "Tag-jump to file or directory",
   {K_F12, K_M_j,       KNA}, F_I(doe_tag_jump_in_cur_line),       get_str_setting_none },

 {EFNM, "",                      "Editor Editing Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFNM, "Tab",                   "Insert a TAB character",
   {K_TAB,         KNA, KNA}, F_I(doe_tab),                        get_str_setting_none },
 {EFNM, "Enter",                 "Insert a carriage return",
   {K_ENTER,       KNA, KNA}, F_I(doe_carriage_return),            get_str_setting_none },
 {EFNM, "Enter w auto indent",   "Insert a carriage return",
   {K_M_ENTER,     KNA, KNA}, F_I(doe_carriage_return_indent),     get_str_setting_none },
 {EFNM, "Backspace",             "Backspace",
   {K_C_H, K_BS,        KNA}, F_I(doe_backspace),                  get_str_setting_none },
 {EFNM, "Backspace(limited)",     "Backspace(limited)",
   {K_MC_H,        KNA, KNA}, F_I(doe_backspace_limited),          get_str_setting_none },
 {EFNM, "Delete",                "Delete a character",
   {K_C_G, K_DEL,       KNA}, F_I(doe_delete_char),                get_str_setting_none },
 {EFNM, "UpperLower",            "Invert upper/lower letter",
   {K_C_W,         KNA, KNA}, F_I(doe_conv_upp_low_letter),        get_str_setting_none },
 {EFNM, "UpperLetter",           "Make upper letter",
   {K_MC_U,        KNA, KNA}, F_I(doe_conv_low_letter),            get_str_setting_none },
 {EFNM, "Ctrl code",             "Input control code",
   {K_M_EXCLA,     KNA, KNA}, F_I(doe_control_code),               get_str_setting_none },
 {EFNM, "Char code",             "Input character code",
   {K_M_AT,        KNA, KNA}, F_I(doe_charcode),                   get_str_setting_none },
 {EFNM, "Memorize column pos.",  "Memorize column position",
   {K_M_APOST,     KNA, KNA}, F_I(doe_memorize_columns),           get_str_setting_none },
 {EFNM, "Fill spaces",           "Fill spaces till the columns",
   {K_M_QUOTA,     KNA, KNA}, F_I(doe_fill_spaces_to_columns),     get_str_setting_none },
 {EFNM, "Paste history",         "Paste from history",
   {K_M_h,         KNA, KNA}, F_I(doe_paste_from_history),         get_str_setting_none },
#ifdef ENABLE_UNDO
 {EFNM, "Undo",                  "Undo",
   {K_M_u, K_M_z,       KNA}, F_I(doe_undo),                       get_str_setting_none },
 {EFNM, "Redo",                  "Redo",
   {K_M_o,         KNA, KNA}, F_I(doe_redo),                       get_str_setting_none },
#endif // ENABLE_UNDO

 {EFNM, "",                      "Editor Search/Replace Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFAM, "SrchB",                 "Search keyword forward",
   {K_S_F03, K_C_RBRAK, KNA}, F_I(doe_search_backward_first),      get_str_setting_none },
 {EFAM, "SrchF",                 "Search keyword backward",
   {K_S_F04, K_C_BAKSL, KNA}, F_I(doe_search_forward_first),       get_str_setting_none },
 {EFAM, "SrchB",                 "Search keyword backward again",
   {K_F03, K_M_a, K_M_s    }, F_I(doe_search_backward_next),       get_str_setting_none },
 {EFAM, "SrchF",                 "Search keyword forward again",
   {K_F04, K_M_f, K_M_d    }, F_I(doe_search_forward_next),        get_str_setting_none },
 {EFNM, "Replace",               "Replace keyword",
   {K_C_CARET,     KNA, KNA}, F_I(doe_replace),                    get_str_setting_none },
#ifdef ENABLE_REGEX
 {EFNM, "Find Bracket()",        "Find counter bracket()",
   {K_M_RBRAK,     KNA, KNA}, F_I(doe_find_bracket),               get_str_setting_none },
 {EFNM, "Find Bracket)(",        "Find counter bracket)(",
   {K_M_LBRAK,     KNA, KNA}, F_I(doe_find_bracket_reverse),       get_str_setting_none },
#endif // ENABLE_REGEX
 {EFNM, "RecKM",                 "Start/Stop recording key-macro",
   {K_F01, K_M_r,       KNA}, F_I(doe_start_rec__cancel_rec),      get_str_setting_none },
 {EFNM, "PlyBk",                 "End-rec/Playback key-macro",
   {K_F02, K_M_p,       KNA}, F_I(doe_end_rec__playback),          get_str_setting_none },
 {EFNM, "Playback-1",            "Playback 1st latest key-macro",
   {K_M_1,         KNA, KNA}, F_I(doe_playback_last_1),            get_str_setting_none },
 {EFNM, "Playback-2",            "Playback 2nd latest key-macro",
   {K_M_2,         KNA, KNA}, F_I(doe_playback_last_2),            get_str_setting_none },
#ifdef ENABLE_HISTORY
 {EFNM, "Playback-string",       "Playback input string",
   {K_M_3,         KNA, KNA}, F_I(doe_playback_string),            get_str_setting_none },
#endif // ENABLE_HISTORY
 {EFAM, "Run line soon(logging)","Run current line soon w/ log",
   {K_M_x,         KNA, KNA}, F_I(doe_run_line_soon),        get_str_setting_none },
 {EFAM, "Run command",           "Run command input",
   {K_M_X,         KNA, KNA}, F_I(doe_run_line_input),             get_str_setting_none },

 {EFNM, "",                      "Editor Buffer Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFAM, "Previous buffer",       "Switch to previous file",
   {K_M_COMMA,     KNA, KNA}, F_I(doe_switch_to_prev_buffer),      get_str_setting_none },
 {EFAM, "Next buffer",           "Switch to next file",
   {K_M_PERIO,     KNA, KNA}, F_I(doe_switch_to_next_buffer),      get_str_setting_none },
 {EFAM, "Top of buffers",        "Switch to top of buffers",
   {K_M_LESST,     KNA, KNA}, F_I(doe_switch_to_prev_bufs_boundary), get_str_setting_none },
 {EFAM, "Bottom of buffers",     "Switch to bottom of buffers",
   {K_M_GREAT,     KNA, KNA}, F_I(doe_switch_to_next_bufs_boundary), get_str_setting_none },
/// {EFAM, "Previous buffers",      "Switch to previous buffers",
///   {KNA,           KNA, KNA}, F_I(doe_switch_to_prev_buffers),     get_str_setting_none },
/// {EFAM, "Next buffers",          "Switch to next buffers",
///   {KNA,           KNA, KNA}, F_I(doe_switch_to_next_buffers),     get_str_setting_none },
 {EFNM, "Open project file",     "Open project file",
   {K_M_P,         KNA, KNA}, F_I(doe_open_proj_file),             get_str_setting_none },
 {EFNM, "Open exec. log file",   "Open exec. log file",
   {K_M_l,         KNA, KNA}, F_I(doe_open_exec_log_file),         get_str_setting_none },
 {EFNM, "Goto prev. pos",        "Goto previous pos.",
   {K_M_SLASH,     KNA, KNA}, F_I(doe_return_to_prev_file_pos),    get_str_setting_none },
#ifdef ENABLE_HELP
 {EFNM, "Splash",                "Splash screen",
   {K_M_v,         KNA, KNA}, F_I(doe_splash),                     get_str_setting_none },
 {EFNM, "File List",             "Display File List",
   {K_M_SEMCO,     KNA, KNA}, F_I(doe_view_file_list),             get_str_setting_none },
 {EFNM, "Key List",              "Display Key List",
   {K_M_QUEST,     KNA, KNA}, F_I(doe_view_func_list),             get_str_setting_none },
#endif // ENABLE_HELP

 {EFNM, "",                      "Editor Cut-buffer Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFAM, "Mark ",                 "Mark text",
   {K_F05, K_C_N, K_M_5    }, F_I(doe_tog_mark),                   get_str_setting_none },
 {EFNM, "Select all",            "Select all of buffer",
   {K_S_F05, K_M_PERCE, KNA}, F_I(doe_select_all_lines),           get_str_setting_none },
 {EFNM, "Cut  ",                 "Cut into Cut-buffer",
   {K_F06, K_C_K, K_M_6    }, F_I(doe_cut_text),                   get_str_setting_none },
 {EFNM, "Cut into clip-board",   "Cut into clip-board",
   {K_S_F06, K_M_K,     KNA}, F_I(doe_cut_text_to_sys_clipboard),  get_str_setting_none },
 {EFNM, "Del  ",                 "Delete text",
   {K_M_k, K_M_CARET,   KNA}, F_I(doe_delete_text),                get_str_setting_none },
 {EFAM, "Copy ",                 "Copy to Cut-buffer",
   {K_F07, K_M_7,       KNA}, F_I(doe_copy_text),                  get_str_setting_none },
 {EFNM, "Copy to clip-board",    "Copy to clip-board",
   {K_S_F07, K_M_C,     KNA}, F_I(doe_copy_text_to_sys_clipboard), get_str_setting_none },
 {EFNM, "Paste",                 "Paste from Cut-buf with pop",
   {K_F08, K_M_8,       KNA}, F_I(doe_paste_text_with_pop),        get_str_setting_none },
 {EFNM, "ClrCB",                 "Clear all cut buffers",
   {K_S_F08, K_M_ASTER, KNA}, F_I(doe_clear_all_cut_buffers),      get_str_setting_none },
 {EFNM, "Paste",                 "Paste from Cut-buf without pop",
   {K_F09, K_M_9, K_INS    }, F_I(doe_paste_text_without_pop),     get_str_setting_none },
 {EFNM, "Dupli",                 "Duplicate line",
   {K_F10, K_M_0,       KNA}, F_I(doe_duplicate_text),             get_str_setting_none },
 {EFNM, "CutToHead",             "Cut to head of the line",
   {K_C_J,         KNA, KNA}, F_I(doe_cut_to_head),                get_str_setting_none },
 {EFNM, "CutToTail",             "Cut to tail of the line",
   {K_C_L,         KNA, KNA}, F_I(doe_cut_to_tail),                get_str_setting_none },
 {EFNM, "DeleteToHead",          "Delete to head of the line",
   {K_C_U,         KNA, KNA}, F_I(doe_cut_to_head),                get_str_setting_none },
 {EFNM, "DeleteToTail",          "Delete to tail of the line",
   {K_C_O,         KNA, KNA}, F_I(doe_cut_to_tail),                get_str_setting_none },

 {EFNM, "",                      "Editor Mode Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFAM, "App mode",              "Increment mode",
   {KNA,           KNA, KNA}, F_I(doe_inc_app_mode),               get_str_app_mode },
 {EFNM, "Split pane",            "Split screen into panes",
   {K_M_VERTB,     KNA, KNA}, F_I(doe_tog_panes),                  get_str_editor_panes },
 {EFNM, "Switch pane",           "Switch editor pane",
   {K_M_TAB, K_M_BAKSL, KNA}, F_I(doe_tog_panex),                  get_str_editor_panex },
 {EFNM, "Draw cursor",           "Toggle Drawing cursor",
   {K_MC_C,        KNA, KNA}, F_I(doe_tog_draw_cursor),            get_str_draw_cursor },
 {EFNM, "Ignore case",           "Toggle Ignore case",
   {K_MC_G,        KNA, KNA}, F_I(doe_tog_ignore_case),            get_str_ignore_case },
 {EFNM, "Display key list",      "Increment Displaying key list",
   {K_MC_K,        KNA, KNA}, F_I(doe_inc_key_list_lines),         get_str_key_list_lines },
 {EFNM, "Back up files",         "Increment Back up files",
   {K_MC_B,        KNA, KNA}, F_I(doe_inc_backup_files),           get_str_backup_files },
#ifdef ENABLE_REGEX
 {EFNM, "RegExp",                "Toggle Regex search/replace",
   {K_MC_X,        KNA, KNA}, F_I(doe_tog_regexp),                 get_str_regexp },
#endif // ENABLE_REGEX
 {EFNM, "Cursor center",         "Increment Cursor-center mode",
   {K_MC_S,        KNA, KNA}, F_I(doe_inc_cursor_positioning),     get_str_cursor_positioning },
 {EFNM, "Dual scroll",           "Toggle Dual scroll",
   {K_MC_D,        KNA, KNA}, F_I(doe_tog_dual_scroll),            get_str_dual_scroll },
 {EFNM, "Show ruler",            "Toggle Show Ruler",
   {K_MC_R,        KNA, KNA}, F_I(doe_tog_show_ruler),             get_str_show_ruler },
 {EFNM, "Show line number",      "Toggle Show Line number",
   {K_MC_N,        KNA, KNA}, F_I(doe_tog_show_line_num),          get_str_show_line_num },
#ifdef ENABLE_SYNTAX
 {EFNM, "Syntax HL",             "Toggle Syntax Highlighting",
   {K_M_H,         KNA, KNA}, F_I(doe_tog_syntax_hl),              get_str_syntax_hl },
 {EFNM, "TAB/EOL notation",      "Toggle TAB/EOL notation",
   {K_MC_Z,        KNA, KNA}, F_I(doe_tog_tab_eol_notation),       get_str_tab_eol_notation },
#endif // ENABLE_SYNTAX

 {EFNM, "",                      "Editor Buffer Mode Menu",
   {KNA,           KNA, KNA}, F_I(doe_menu_0),                     get_str_setting_none },
 {EFNM, "nix format",            "Set nix format (LF)",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_nix_file),           get_str_buf_nix_file },
 {EFNM, "Mac format",            "Set Mac format (CR)",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_mac_file),           get_str_buf_mac_file },
 {EFNM, "DOS format",            "Set DOS format (CR+LF)",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_dos_file),           get_str_buf_dos_file },
 {EFNM, "ASCII  encoding",       "Set ASCII  encoding",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_enc_ascii),          get_str_buf_enc_ascii },
 {EFNM, "UTF-8  encoding",       "Set UTF-8  encoding",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_enc_utf8),           get_str_buf_enc_utf8 },
#ifdef USE_NKF
 {EFNM, "EUC-JP encoding",       "Set EUC-JP encoding",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_enc_eucjp),          get_str_buf_enc_eucjp },
 {EFNM, "S-JIS  encoding",       "Set S-JIS  encoding",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_enc_sjis),           get_str_buf_enc_sjis },
 {EFNM, "JIS    encoding",       "Set JIS    encoding",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_enc_jis),            get_str_buf_enc_jis },
#endif // USE_NKF
 {EFNM, "BINARY encoding",       "Set BINARY encoding",
   {KNA,           KNA, KNA}, F_I(doe_set_buf_enc_binary),         get_str_buf_enc_binary },
 {EFNM, "Tab size",              "Toggle Tab size",
   {K_MC_T,        KNA, KNA}, F_I(doe_tog_buf_tab_size),           get_str_buf_tab_size },
 {EFNM, "Tab size",              "Increment Tab size",
   {K_MC_Y,        KNA, KNA}, F_I(doe_inc_buf_tab_size),           get_str_buf_tab_size },
 {EFNM, "Line-wrap mode",        "Toggle Line-wrap mode",
   {K_MC_W,        KNA, KNA}, F_I(doe_tog_buf_line_wrap_mode),     get_str_buf_line_wrap_mode },

 {EFNM, "",                      "",
   {KNA,           KNA, KNA}, F_I(NULL), NULL },
};

// End of editorkeys.c
